Basic FERC data extraction metrics
catalyst-cooperative/ferc-xbrl-extractor pull request #117
Opened 2023-08-16 15:18 UTC by jdangerx

After a surprisingly long development cycle, which I'll unpack later, we have some tests that run on a subset of FERC data that spans multiple forms & multiple years.

I decided to sample the data because I found running these metrics across all the FERC XBRL data we have access to, to take a really long time (>1h) and because I didn't want to have to set up Git LFS to Store all these Large Files. Happy to test against everything, but see the note about empty file handling at the bottom.

They measure:
* lost fact %
* non-null values exist in every row
* primary key uniqueness

During development, I refactored some aspects of `extract()` to be easier to test. I haven't looked into downstream impacts on PUDL yet.

I also found some issues with empty file handling, and might have to refactor further to properly handle those, but that's out of scope of this PR.

2023-08-16 18:28 UTC, jdangerx commented
Ahh, realizing I didn't run `pre-commit install` for this repo. Which is why none of my pre-commit checks were running before 😅

2023-08-21 20:18 UTC, jdangerx commented on tests/integration/console_scripts_test.py
These changes are mostly to fix the usage of pkg_resources and to clean up after ourselves in test.

2023-08-21 20:18 UTC, jdangerx commented on tests/integration/datapackage_test.py
> +                    'cid_1,EID1,filing,2021-01-01,2021-12-31,total,"value 1","value 2"\n'
These should fix the tests that are failing on `main` right now.

2023-08-21 20:18 UTC, jdangerx commented on src/ferc_xbrl_extractor/cli.py
> +    tables = xbrl.get_fact_tables(
Pulling taxonomy generation out of the main `extract` function makes the interface simpler, but also lets us not double-generate the taxonomies.

2023-08-21 20:18 UTC, jdangerx commented
I think @zschira is still the right one to review, but FYI @zaneselvans if you were curious about the test issues.

2023-08-22 18:03 UTC, zschira requested changes
Looks good! One small nit about return types, and I think we should make sure to get the logging for duplicate facts implemented here somewhere, but otherwise I'm good to merge

2023-08-23 13:14 UTC, jdangerx commented on tests/integration/datapackage_test.py
> +                    'cid_1,EID1,filing,2021-01-01,2021-12-31,total,"value 1","value 2"\n'
I think it was probably my diff that kept the capital T in when I reformatted the test data.

2023-08-23 13:41 UTC, jdangerx commented
I just added the logs & fixed the type signature! I think we have two options here:

1. merge this (once review passes), knowing that there are still some issues with empty files & deep deduplication; then, get #124 in as a follow-up
2. close this and then review #124 as a PR against `main`

I have a light (3/10) preference for keeping these PRs split, but @zschira you're the reviewer - let me know if you have a stronger preference!

2023-08-23 13:42 UTC, jdangerx commented on src/ferc_xbrl_extractor/instance.py
> +        self.all_fact_ids = {
Good thought! After adding this, I'm finding that this is logging quite a few duplicate facts for some forms. But the deduplication, even the simple version in this PR, seems to handle them nicely :)

2023-08-23 14:49 UTC, zschira approved these changes

2023-08-23 15:21 UTC, merged